name: Build and Publish Docker

on:
  push:
    paths:
      - etc/*
    branches:
      - main
    tags:
      - v1.*
      - v2.*
      - v3.*
env:
  NAME: user-rpc
  NAMESPACE: bigrocs
  REGISTRY: registry.cn-hongkong.aliyuncs.com
  ACCES_STOKEN: ${{ secrets.ACCES_STOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: ${{ env.NAMESPACE }}/${{ env.ACCES_STOKEN }}
          dockerfile: ./Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ env.REGISTRY }}
          buildargs: ${{ env.ACCES_STOKEN }}
          tag_names: true