name: Build and Publish Docker

on:
  push:
    branches:
      - main
    tags:
      - v1.*
      - v2.*
      - v3.*
      
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      registry: registry.cn-hongkong.aliyuncs.com
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        run: |
          echo ${{ steps.build.outputs.registry }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ steps.build.outputs.registry }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.build.outputs.registry }}/bigrocs/go-rocs:latest