name: Build and Publish Docker

on:
  push:
    branches:
      - main
    tags:
      - v1.*
      - v2.*
      - v3.*
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        env:
          REGISTRY_URL: registry.cn-hongkong.aliyuncs.com
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: REGISTRY_URL
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: REGISTRY_URL/bigrocs/go-rocs:latest