name: Build and Publish Docker

on:
  push:
    branches:
      - main
    tags:
      - v1.*
      - v2.*
      - v3.*
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: registry.cn-hongkong.aliyuncs.com

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      registry: registry.cn-hongkong.aliyuncs.com
    steps:
      # -
      #   name: Checkout
      #   uses: actions/checkout@v3
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      -
        name: echo github.repository
        run: | 
          TAGS=${ GITHUB_REF_NAME }
          if [ $TAGS == "main" ]; then
              TAGS="latest"
          fi
          echo $TAGS
          set
      -
        name: echo github.TAGS
        run: | 
          echo ${ GITHUB_REF_NAME }
          set
      # -
      #   name: Login to ${{ env.REGISTRY }}
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ env.REGISTRY }}/bigrocs/go-rocs:latest