name: Build user-rpc and Publish Docker

on:
  push:
    paths:
      - etc/*
    branches:
      - main
    tags:
      - v1.*
      - v2.*
      - v3.*
env:
  NAME: user-rpc
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: ${{ secrets.DOCKER_NAMESPACE }}/${{ env.NAME }}
          dockerfile: ./Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          buildargs: ${{ secrets.ACCES_STOKEN }}
          tag_names: true